// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/interfaces.go -destination=internal/mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/alnoi/pr-reviewer-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPRUseCase is a mock of PRUseCase interface.
type MockPRUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPRUseCaseMockRecorder
	isgomock struct{}
}

// MockPRUseCaseMockRecorder is the mock recorder for MockPRUseCase.
type MockPRUseCaseMockRecorder struct {
	mock *MockPRUseCase
}

// NewMockPRUseCase creates a new mock instance.
func NewMockPRUseCase(ctrl *gomock.Controller) *MockPRUseCase {
	mock := &MockPRUseCase{ctrl: ctrl}
	mock.recorder = &MockPRUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRUseCase) EXPECT() *MockPRUseCaseMockRecorder {
	return m.recorder
}

// CreatePR mocks base method.
func (m *MockPRUseCase) CreatePR(ctx context.Context, prID, prName, authorID string) (domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, prID, prName, authorID)
	ret0, _ := ret[0].(domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockPRUseCaseMockRecorder) CreatePR(ctx, prID, prName, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockPRUseCase)(nil).CreatePR), ctx, prID, prName, authorID)
}

// MergePR mocks base method.
func (m *MockPRUseCase) MergePR(ctx context.Context, prID string) (domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, prID)
	ret0, _ := ret[0].(domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePR indicates an expected call of MergePR.
func (mr *MockPRUseCaseMockRecorder) MergePR(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockPRUseCase)(nil).MergePR), ctx, prID)
}

// ReassignReviewer mocks base method.
func (m *MockPRUseCase) ReassignReviewer(ctx context.Context, prID, oldUserID string) (domain.PullRequest, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", ctx, prID, oldUserID)
	ret0, _ := ret[0].(domain.PullRequest)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockPRUseCaseMockRecorder) ReassignReviewer(ctx, prID, oldUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockPRUseCase)(nil).ReassignReviewer), ctx, prID, oldUserID)
}

// MockStatsUseCase is a mock of StatsUseCase interface.
type MockStatsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockStatsUseCaseMockRecorder
	isgomock struct{}
}

// MockStatsUseCaseMockRecorder is the mock recorder for MockStatsUseCase.
type MockStatsUseCaseMockRecorder struct {
	mock *MockStatsUseCase
}

// NewMockStatsUseCase creates a new mock instance.
func NewMockStatsUseCase(ctrl *gomock.Controller) *MockStatsUseCase {
	mock := &MockStatsUseCase{ctrl: ctrl}
	mock.recorder = &MockStatsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsUseCase) EXPECT() *MockStatsUseCaseMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsUseCase) GetStats(ctx context.Context) (domain.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(domain.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsUseCaseMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsUseCase)(nil).GetStats), ctx)
}

// MockTeamUseCase is a mock of TeamUseCase interface.
type MockTeamUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTeamUseCaseMockRecorder
	isgomock struct{}
}

// MockTeamUseCaseMockRecorder is the mock recorder for MockTeamUseCase.
type MockTeamUseCaseMockRecorder struct {
	mock *MockTeamUseCase
}

// NewMockTeamUseCase creates a new mock instance.
func NewMockTeamUseCase(ctrl *gomock.Controller) *MockTeamUseCase {
	mock := &MockTeamUseCase{ctrl: ctrl}
	mock.recorder = &MockTeamUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamUseCase) EXPECT() *MockTeamUseCaseMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockTeamUseCase) CreateTeam(ctx context.Context, team domain.Team) (domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, team)
	ret0, _ := ret[0].(domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamUseCaseMockRecorder) CreateTeam(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeamUseCase)(nil).CreateTeam), ctx, team)
}

// DeactivateTeamMembers mocks base method.
func (m *MockTeamUseCase) DeactivateTeamMembers(ctx context.Context, teamName string, userIDs []string) (domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateTeamMembers", ctx, teamName, userIDs)
	ret0, _ := ret[0].(domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateTeamMembers indicates an expected call of DeactivateTeamMembers.
func (mr *MockTeamUseCaseMockRecorder) DeactivateTeamMembers(ctx, teamName, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateTeamMembers", reflect.TypeOf((*MockTeamUseCase)(nil).DeactivateTeamMembers), ctx, teamName, userIDs)
}

// GetTeam mocks base method.
func (m *MockTeamUseCase) GetTeam(ctx context.Context, teamName string) (domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, teamName)
	ret0, _ := ret[0].(domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamUseCaseMockRecorder) GetTeam(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeamUseCase)(nil).GetTeam), ctx, teamName)
}

// MockUserUseCase is a mock of UserUseCase interface.
type MockUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUseCaseMockRecorder
	isgomock struct{}
}

// MockUserUseCaseMockRecorder is the mock recorder for MockUserUseCase.
type MockUserUseCaseMockRecorder struct {
	mock *MockUserUseCase
}

// NewMockUserUseCase creates a new mock instance.
func NewMockUserUseCase(ctrl *gomock.Controller) *MockUserUseCase {
	mock := &MockUserUseCase{ctrl: ctrl}
	mock.recorder = &MockUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUseCase) EXPECT() *MockUserUseCaseMockRecorder {
	return m.recorder
}

// GetUserReviewPRs mocks base method.
func (m *MockUserUseCase) GetUserReviewPRs(ctx context.Context, userID string) ([]domain.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviewPRs", ctx, userID)
	ret0, _ := ret[0].([]domain.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviewPRs indicates an expected call of GetUserReviewPRs.
func (mr *MockUserUseCaseMockRecorder) GetUserReviewPRs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviewPRs", reflect.TypeOf((*MockUserUseCase)(nil).GetUserReviewPRs), ctx, userID)
}

// SetUserIsActive mocks base method.
func (m *MockUserUseCase) SetUserIsActive(ctx context.Context, userID string, isActive bool) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserIsActive indicates an expected call of SetUserIsActive.
func (mr *MockUserUseCaseMockRecorder) SetUserIsActive(ctx, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserIsActive", reflect.TypeOf((*MockUserUseCase)(nil).SetUserIsActive), ctx, userID, isActive)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// WithTx mocks base method.
func (m *MockTransactor) WithTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTransactorMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTransactor)(nil).WithTx), ctx, fn)
}
