// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces.go -destination=internal/mocks/mock_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/alnoi/pr-reviewer-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockTeamRepository) CreateTeam(ctx context.Context, teamName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, teamName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamRepositoryMockRecorder) CreateTeam(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeamRepository)(nil).CreateTeam), ctx, teamName)
}

// GetTeam mocks base method.
func (m *MockTeamRepository) GetTeam(ctx context.Context, teamName string) (domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, teamName)
	ret0, _ := ret[0].(domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamRepositoryMockRecorder) GetTeam(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeamRepository)(nil).GetTeam), ctx, teamName)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetTeamMembers mocks base method.
func (m *MockUserRepository) GetTeamMembers(ctx context.Context, teamName string, onlyActive bool) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamMembers", ctx, teamName, onlyActive)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamMembers indicates an expected call of GetTeamMembers.
func (mr *MockUserRepositoryMockRecorder) GetTeamMembers(ctx, teamName, onlyActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamMembers", reflect.TypeOf((*MockUserRepository)(nil).GetTeamMembers), ctx, teamName, onlyActive)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, userID string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, userID)
}

// SetUserIsActive mocks base method.
func (m *MockUserRepository) SetUserIsActive(ctx context.Context, userID string, isActive bool) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserIsActive indicates an expected call of SetUserIsActive.
func (mr *MockUserRepositoryMockRecorder) SetUserIsActive(ctx, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserIsActive", reflect.TypeOf((*MockUserRepository)(nil).SetUserIsActive), ctx, userID, isActive)
}

// UpsertUsers mocks base method.
func (m *MockUserRepository) UpsertUsers(ctx context.Context, teamName string, members []domain.TeamMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUsers", ctx, teamName, members)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUsers indicates an expected call of UpsertUsers.
func (mr *MockUserRepositoryMockRecorder) UpsertUsers(ctx, teamName, members any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUsers", reflect.TypeOf((*MockUserRepository)(nil).UpsertUsers), ctx, teamName, members)
}

// MockPRRepository is a mock of PRRepository interface.
type MockPRRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPRRepositoryMockRecorder
	isgomock struct{}
}

// MockPRRepositoryMockRecorder is the mock recorder for MockPRRepository.
type MockPRRepositoryMockRecorder struct {
	mock *MockPRRepository
}

// NewMockPRRepository creates a new mock instance.
func NewMockPRRepository(ctrl *gomock.Controller) *MockPRRepository {
	mock := &MockPRRepository{ctrl: ctrl}
	mock.recorder = &MockPRRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRRepository) EXPECT() *MockPRRepositoryMockRecorder {
	return m.recorder
}

// CreatePR mocks base method.
func (m *MockPRRepository) CreatePR(ctx context.Context, pr domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockPRRepositoryMockRecorder) CreatePR(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockPRRepository)(nil).CreatePR), ctx, pr)
}

// GetAssignmentsCountByUser mocks base method.
func (m *MockPRRepository) GetAssignmentsCountByUser(ctx context.Context) ([]domain.UserAssignmentsStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignmentsCountByUser", ctx)
	ret0, _ := ret[0].([]domain.UserAssignmentsStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignmentsCountByUser indicates an expected call of GetAssignmentsCountByUser.
func (mr *MockPRRepositoryMockRecorder) GetAssignmentsCountByUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignmentsCountByUser", reflect.TypeOf((*MockPRRepository)(nil).GetAssignmentsCountByUser), ctx)
}

// GetOpenPRsByReviewers mocks base method.
func (m *MockPRRepository) GetOpenPRsByReviewers(ctx context.Context, userIDs []string) ([]domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenPRsByReviewers", ctx, userIDs)
	ret0, _ := ret[0].([]domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenPRsByReviewers indicates an expected call of GetOpenPRsByReviewers.
func (mr *MockPRRepositoryMockRecorder) GetOpenPRsByReviewers(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenPRsByReviewers", reflect.TypeOf((*MockPRRepository)(nil).GetOpenPRsByReviewers), ctx, userIDs)
}

// GetPR mocks base method.
func (m *MockPRRepository) GetPR(ctx context.Context, prID string) (domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPR", ctx, prID)
	ret0, _ := ret[0].(domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPR indicates an expected call of GetPR.
func (mr *MockPRRepositoryMockRecorder) GetPR(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPR", reflect.TypeOf((*MockPRRepository)(nil).GetPR), ctx, prID)
}

// GetPRReviewers mocks base method.
func (m *MockPRRepository) GetPRReviewers(ctx context.Context, prID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRReviewers", ctx, prID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRReviewers indicates an expected call of GetPRReviewers.
func (mr *MockPRRepositoryMockRecorder) GetPRReviewers(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRReviewers", reflect.TypeOf((*MockPRRepository)(nil).GetPRReviewers), ctx, prID)
}

// GetPRStatusCounts mocks base method.
func (m *MockPRRepository) GetPRStatusCounts(ctx context.Context) (domain.PRStatusCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRStatusCounts", ctx)
	ret0, _ := ret[0].(domain.PRStatusCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRStatusCounts indicates an expected call of GetPRStatusCounts.
func (mr *MockPRRepositoryMockRecorder) GetPRStatusCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRStatusCounts", reflect.TypeOf((*MockPRRepository)(nil).GetPRStatusCounts), ctx)
}

// GetPRsWhereReviewer mocks base method.
func (m *MockPRRepository) GetPRsWhereReviewer(ctx context.Context, userID string) ([]domain.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRsWhereReviewer", ctx, userID)
	ret0, _ := ret[0].([]domain.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRsWhereReviewer indicates an expected call of GetPRsWhereReviewer.
func (mr *MockPRRepositoryMockRecorder) GetPRsWhereReviewer(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRsWhereReviewer", reflect.TypeOf((*MockPRRepository)(nil).GetPRsWhereReviewer), ctx, userID)
}

// PRExists mocks base method.
func (m *MockPRRepository) PRExists(ctx context.Context, prID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PRExists", ctx, prID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PRExists indicates an expected call of PRExists.
func (mr *MockPRRepositoryMockRecorder) PRExists(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PRExists", reflect.TypeOf((*MockPRRepository)(nil).PRExists), ctx, prID)
}

// SetPRReviewers mocks base method.
func (m *MockPRRepository) SetPRReviewers(ctx context.Context, prID string, reviewers []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPRReviewers", ctx, prID, reviewers)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPRReviewers indicates an expected call of SetPRReviewers.
func (mr *MockPRRepositoryMockRecorder) SetPRReviewers(ctx, prID, reviewers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPRReviewers", reflect.TypeOf((*MockPRRepository)(nil).SetPRReviewers), ctx, prID, reviewers)
}

// UpdatePR mocks base method.
func (m *MockPRRepository) UpdatePR(ctx context.Context, pr domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePR", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePR indicates an expected call of UpdatePR.
func (mr *MockPRRepositoryMockRecorder) UpdatePR(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePR", reflect.TypeOf((*MockPRRepository)(nil).UpdatePR), ctx, pr)
}
